### ISSUE TITLE
Ingame Level Editor

### ISSUE THREAD

**Issue by DaivyIsHere** [kuviman/linksider#43]
Do this after most stuffs from the original version are implemented

**Comment by DaivyIsHere** [comment]
- [ ] Fix the rotation issue of some brushes
- [ ] Set player index (effects which player you start on and the order when you switch player)
- [ ] Add new level
- [ ] Duplicate level
- [ ] Delete level
- [ ] Rename level name
- [ ] Show current level index and name
- [ ] Reorder level

Polish
- [ ] Indicate you're in editing mode
- [ ] Show if the level is saved or not. Show how many changes since you start editing (or since last save)?

**Comment by kuviman** [comment]
EZ
