### ISSUE TITLE
Some small improvement requests

### ISSUE THREAD

**Issue by DaivyIsHere** [kuviman/linksider#63]
- [x] Reverse the group vertical layout. The first group will be at the top and the next group will be under the first group
- [ ] Make the rename UI popup smaller like a message box maybe, or make it transparent?
- [x] A warning question for unsaved changes if I exit without saving (even when I just close the whole game window? idk if it's possible)
- [x] When I undo all the changes I made, the unsaved changes warning should disppear
- [x] I think redo is broken for some reasons

**Comment by kuviman** [comment]
point to got into own issue #65
